"""Set ``Signal.created_at`` to the instant each analysis started.

``Signal.trace_id``, where present, is generated by
``llm_traces.new_run_id()`` as ``"<YYYYMMDDTHHMMSS>-<8 hex chars>"`` — the UTC
instant the analysis started. That instant is already sitting in the database
as a string; recovering it needs no file I/O and does not depend on the trace
file itself still existing on disk.

**This rewrites rows that already hold a value, and that is the point.** Until
2026-09-11 ``created_at`` meant two different things: ``db.record_signal``
stored the moment the analysis *finished*, while rows recovered by an earlier
version of this script held the *start*. An analysis takes about sixteen
minutes on this hardware, so the two readings sat far apart with nothing
marking the seam. One meaning now — the start — because it is the instant that
was really observed, where a finish would have to be computed. See the
2026-09-11 entry in JOURNEY.md.

Rows with no ``trace_id`` (``LLM_TRACE_DIR`` was unset when the analysis ran)
are left exactly as they are. There is nothing to recover them from, and
guessing would put a time in the record nobody observed — the same reason
``evaluated_at``/``trigger`` stay NULL on rows that predate them.

    python -m backend.scripts.backfill_signal_timestamps [--dry-run]
"""
import argparse
import datetime

from backend.database import db


def timestamp_from_trace_id(trace_id: str) -> datetime.datetime | None:
    """The UTC instant encoded in a trace_id, or None if it doesn't parse —
    defensive against a trace_id that was ever produced a different way."""
    stamp = trace_id.split("-", 1)[0]
    try:
        return datetime.datetime.strptime(stamp, "%Y%m%dT%H%M%S")
    except ValueError:
        return None


def _drift_seconds(stored, started: datetime.datetime) -> float | None:
    """How far the stored value sits from the run's start, or None when there
    is nothing stored to compare."""
    if stored is None:
        return None
    if not isinstance(stored, datetime.datetime):
        try:
            stored = datetime.datetime.fromisoformat(str(stored))
        except ValueError:
            return None
    if stored.tzinfo is not None:
        stored = stored.replace(tzinfo=None)
    return (stored - started).total_seconds()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--dry-run", action="store_true", help="report what would change; write nothing"
    )
    args = parser.parse_args()

    candidates = db.get_signals_with_trace()
    if not candidates:
        print("No signal carries a trace_id — nothing can be recovered.")
        return 0

    corrected = 0
    already = 0
    unreadable = 0
    for signal in candidates:
        # get_signals_with_trace filters these out, but the guard keeps the
        # script correct whatever feeds it a row.
        started = timestamp_from_trace_id(signal.trace_id) if signal.trace_id else None
        if started is None:
            unreadable += 1
            print(f"  {signal.ticker} #{signal.id}: left alone — unreadable trace_id {signal.trace_id!r}")
            continue
        drift = _drift_seconds(signal.created_at, started)
        if drift is not None and abs(drift) < 1:
            already += 1
            continue
        corrected += 1
        was = "NULL" if signal.created_at is None else f"{signal.created_at} ({drift:+.0f}s)"
        print(f"  {signal.ticker} #{signal.id}: {was} -> {started.isoformat()}")
        if not args.dry_run:
            db.set_signal_created_at(signal.id, started)

    print()
    print(
        f"{corrected} set to the run's start, {already} already correct, "
        f"{unreadable} left alone (no usable trace_id)."
    )
    if args.dry_run:
        print("Dry run — nothing written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
